eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    instance-info-replication-interval-seconds: 5
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka

server:
  port: 8765
  error:
    include-stacktrace: never

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  datasource:
    password: '12345'
    username: root
    url: jdbc:mysql://localhost:3306/mydb
  application:
    name: ecommerce-api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: shopping-api
            uri: lb://shopping-api
            predicates:
              - Path=/ecommerce/shopping/**
              #filters:
              # - AuthenticationFilter

          - id: user-api
            uri: lb://user-api
            predicates:
              - Path=/ecommerce/usuarios/**
            #filters:
            #  - AuthenticationFilter

          - id: product-api
            uri: lb://product-api
            predicates:
              - Path=/ecommerce/produtos/**
            #filters:
            # - AuthenticationFilter

  #        - id: auth-api
  #          uri: lb://auth-api
  #          predicates:
  #            - Path=/ibm/auth/**
feign:
  user-api:
    name: user-api #EcomUserApi
    url: http://localhost:8765/ecommerce/usuarios/